export const PARTNER_KEY_UPDATED = 'PARTNER_KEY_UPDATED';
export const DETAILS_UPDATED = 'DETAILS_UPDATED';
export const POST_DETAILS_FIRST_SUCCESS = 'POST_DETAILS_FIRST_SUCCESS';
export const POST_DETAILS_FIRST_REQUEST = 'POST_DETAILS_FIRST_REQUEST';
export const POST_DETAILS_FIRST_FAILURE = 'POST_DETAILS_FIRST_FAILURE';
export const E_COMERCE_SUPORTED_UPDATED = 'E_COMERCE_SUPORTED_UPDATED';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';